### PR TITLE
Reservation - Promo Content API

### PR DESCRIPTION
**Pull request by ashitosh-wagh**
https://digitizework.atlassian.net/browse/IOHOU-6221

### CODE REVIEW

**Comment by ashitosh-wagh** [comment]
Response Screenshots :- 

image

image

image

image

image

image

image

**Review by hrishikesh-ioffice — APPROVED** [review]
Looks good

**Comment by ashitosh-wagh** [comment]
Updated the complete PR.

image

image

**Review by kmadanwad-cybage — APPROVED** [review]
Looks good. Approved!

**Pull request merged**
