### PR TITLE
Added Sensors related APIs to Space module endpoints

### PR DESCRIPTION
**Pull request by Cybage-Rushikesh**
Sensors:
Retrieve Sensors:
image

Retrieve Sensor Types:
image

Retrieve Sensor Rooms:
image

Add/Move/Deallocate Sensor:
image

image

image

Update Sensor:
image

Retrieve Sensor Live Room Data and People Count:
image

Jira Link: https://digitizework.atlassian.net/browse/IOHOU-6051

### CODE REVIEW

**Review by hrishikesh-ioffice — COMMENTED** [review]
@Cybage-Rushikesh  for /sensors/live-room-utilization and /sensors/live-room-people-count there's an empty object in response, you can add some data there so that we know the schema of response object.

**Comment by Cybage-Rushikesh** [comment]
> @Cybage-Rushikesh for /sensors/live-room-utilization and /sensors/live-room-people-count there's an empty object in response, you can add some data there so that we know the schema of response object.

@hrishikesh-ioffice  As discussed with you earlier, the data for those APIs which may return Non-empty object is unavailable in any of our available Staging and Production environments. Also, you tried to find the same on dream team sites but couldn't find it. In the available environments we get only the responses which are already documented in this PR. Kindly confirm once the implementation and let us know if data can be created by any means/way. Thank you.

**Review by yogeshA-iOffice — APPROVED** [review]
approved

**Comment by hrishikesh-ioffice** [comment]
> > @Cybage-Rushikesh for /sensors/live-room-utilization and /sensors/live-room-people-count there's an empty object in response, you can add some data there so that we know the schema of response object.
> 
> @hrishikesh-ioffice As discussed with you earlier, the data for those APIs which may return Non-empty object is unavailable in any of our available Staging and Production environments. Also, you tried to find the same on dream team sites but couldn't find it. In the available environments we get only the responses which are already documented in this PR. Kindly confirm once the implementation and let us know if data can be created by any means/way. Thank you.

Okay I'll approve this PR since the sensor live data is not present for any of the environments.

**Review by hrishikesh-ioffice — APPROVED** [review]

**Pull request merged**
