### PR TITLE
IOHOU-6050 & IOHOU-6052 - Added APIs for Devices and Buliding Position

### PR DESCRIPTION
**Pull request by Cybage-Rushikesh**
https://digitizework.atlassian.net/browse/IOHOU-6052
https://digitizework.atlassian.net/browse/IOHOU-6050

image
image
image
image
image

### CODE REVIEW

**Review by hrishikesh-ioffice — APPROVED** [review]
looks good to me

**Review by kmadanwad-cybage — CHANGES_REQUESTED** [review]
Please find my review below

- `/devices` is duplicated. Please update the url params and keep only one api
- Move `/floors/markers` and `/floors/markers/types/` to floor section
- `/buildings/{id}` is exiting, please remove

**Comment by Cybage-Rushikesh** [comment]
> Please find my review below
> 
> * `/devices` is duplicated. Please update the url params and keep only one api

Done.
image

**Comment by Cybage-Rushikesh** [comment]
> Please find my review below
> * Move `/floors/markers` and `/floors/markers/types/` to floor section
Done.
image

**Comment by Cybage-Rushikesh** [comment]
> Please find my review below
> * `/buildings/{id}` is exiting, please remove

Done.
image

**Review by kmadanwad-cybage — APPROVED** [review]
Looks good to me!

**Pull request merged**
