### PR TITLE
IOHOU-6054 | Added APIs of Space Desktop Annotations, Layers, Marker Groups

### PR DESCRIPTION
**Pull request by Cybage-Rushikesh**
https://digitizework.atlassian.net/browse/IOHOU-6054

image
image
image
image
image

### CODE REVIEW

**Review by kmadanwad-cybage — CHANGES_REQUESTED** [review]
Please find my review 
- `POST /floors/annotations` I see this api mentioned 4 times, no request body is mentioned. Also two of these return `200` response and two return `201`. What is the logic behind it? I feel api returning `200` should be a `PUT` request. Can you confirm this ?

- Similar case is also with `/floors/markers/group`. Can you confirm if api returning `200` is a `PUT` or 'POST'. If it is `POST` what is the difference between these two apis?

**Comment by Cybage-Rushikesh** [comment]
> Please find my review
> 
> * `POST /floors/annotations` I see this api mentioned 4 times, no request body is mentioned. Also two of these return `200` response and two return `201`. What is the logic behind it? I feel api returning `200` should be a `PUT` request. Can you confirm this ?
> * Similar case is also with `/floors/markers/group`. Can you confirm if api returning `200` is a `PUT` or 'POST'. If it is `POST` what is the difference between these two apis?

 As per discussion,
1) Here, implementation is like, Same POST /floors/annotations API is being used for Creating Annotation as well as Updating Annotation of 3 different types, with the minor difference in request header parameters and response codes. So it was documented separately by me caused repetition of 4 times. 
Changes Done: 
Now, instead of documenting API for each annotation type,  documented only 2 generic APIs for Create and Update Annotation. Also, mentioned the details about the difference in request body for each annotation type and response codes.
Create Annotation:
image
Update Annotation:
image


Also, We have confirmed about 200 and 201 response. Below are the observations: 
There are two response codes available for same POST API call, one returns 201 first time while create operation happens. and one returns 200 while performing update operation and strange thing is PUT is NOT used here for this Update operation :-)

2) Similar changes w.r.t point-1) are done for the Layers and Marker Group APIs as well.

Create Layer:
image
Update Layer:
image

Create Marker Group:
image

Update Marker Group:
image

**Review by kmadanwad-cybage — APPROVED** [review]
Nice work! Thank you.

**Comment by Cybage-Rushikesh** [comment]
> Nice work! Thank you.

Thank you :-)

**Review by hrishikesh-ioffice — APPROVED** [review]
looks good

**Pull request merged**
