### PR TITLE
IOHOU-6049 [Added API for Space Types]

### PR DESCRIPTION
**Pull request by Cybage-Rushikesh**
https://digitizework.atlassian.net/browse/IOHOU-6049
image
image

### CODE REVIEW

**Review by kmadanwad-cybage — CHANGES_REQUESTED** [review]
Please update sample response for api referring to staging sites or dreamteam site instead of automation regression site.

**Comment by Cybage-Rushikesh** [comment]
> Please update sample response for api referring to staging sites or dreamteam site instead of automation regression site.

Done. Updated sample response for api referring to staging sites.

**Review by kmadanwad-cybage — APPROVED** [review]
Look good to me!

**Review by hrishikesh-ioffice — APPROVED** [review]
looks good

**Pull request merged**
